name: 'Build environment setup'
description: 'Reads the configuration file and setup the environment variables'
inputs:
  config-file:
    description: 'Relative path under $GITHUB_WORKSPACE where the build.json is located.'
    required: false
    default: $GITHUB_WORKSPACE/.metadata/build.json

runs:
  using: "composite"
  steps:
    - run: |
          ls  ${{ github.action_path }}
      shell: sh  
    - run: |
          python ${{ github.action_path }}/setup_env.py ${{ inputs.config-file }}
      shell: sh
    