name: 'Build environment setup'
description: 'Checkout the source code and setup the environment variables'
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository.'
    required: false   
  config-file:
    description: 'Relative path under $GITHUB_WORKSPACE where the build.json is located.'
    required: false
    default: $GITHUB_WORKSPACE/.metadata/build.json

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        path: ${{ inputs.path }}
    - run: |
          python ${{ github.action_path }}/setup_env.py ${{ inputs.config-file }}
      shell: bash
    